version: "3.3"

services:
  ###########
  flaskback:
    image: flaskback:1.0
    container_name: flaskback
    environment:
      - PYTHONPATH=/app
    ports:
      - "4433:4433"
    volumes:
      - ./src:/app/src #optional
      - ./client_secret:/app/client_secret
      - ./config:/app/config
    # restart: unless-stopped
